default_stages: [commit]
repos:
  - repo: https://github.com/jorisroovers/gitlint
    rev:  v0.17.0
    hooks:
    - id: gitlint
      stages: [commit-msg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-added-large-files
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    - id: isort
      args:
      - --check
      - --diff
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
      args:
      - --check
      - --diff
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.4.0
    hooks:
    - id: editorconfig-checker
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    - id: bandit
      exclude: tests
  - repo: https://github.com/hadolint/hadolint
    rev: v2.10.0
    hooks:
    - id: hadolint-docker
