services:
  python-project-template:
    container_name: ${PROJECT_NAME}
    image: ${PROJECT_NAME}
    user: ${PROJECT_NAME}
    hostname: docker
    working_dir: ${WORK_DIR}
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        PROJECT_NAME: ${PROJECT_NAME}
        WORK_DIR: ${WORK_DIR}
    volumes:
      - type: bind
        source: ./
        target: ${WORK_DIR}/
      - ${WORK_DIR}/.venv
