from typing import List, Optional

from _typeshed import Incomplete

COMMA: str
DEFAULT: str
UNDERLINE: str
COLORS: Incomplete

def format_options(options: List[str]) -> str: ...
def get_color(color: str) -> str: ...
def underline_text(text: str, color: Optional[str] = ...) -> str: ...
def color_text(text: str, color: str) -> str: ...
def get_print_length(message: str) -> int: ...
def print_flashy(message: str) -> None: ...
